# Generated by Django 3.0.5 on 2020-06-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='discription',
            field=models.TextField(default=2, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
