# Generated by Django 3.0.5 on 2020-06-03 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200603_1841'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
